- name: to configure the backend servers
  hosts: backend
  become: yes
  vars:


  tasks:
  - name: To disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: To enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: To install node js
    ansible.builtin.package:
     name: nodejs
     state: present
