- name: to configure the backend servers
  hosts: backend
  become: yes
  vars:


  tasks:
  - name: To disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: To disable default nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
