- name: To configure mysql
  hosts: mysql
  become: yes
  vars:
   host_address: mysql.app789.site
   password: ExpenseApp@1

  tasks:
  - name: To install Pymysql
    ansible.builtin.pip:
     name: 
     - PyMySQL
     executable: pip3.9

  - name: To install sql server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: To install sql server
    ansible.builtin.service:
     name: mysql-server
     state: started
