- name: To configure backend servers
  hosts: mysql
  become: yes
  vars:
   password: ExpenseApp@1
   host_name: mysql.app789.site

  tasks:
  - name: To install pymysql
    ansible.builtin.pip:
     name:
     - PyMysql
    executable: pip3.9
  
  - name: To install sql server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: To install sql server
    ansible.builtin.package:
     name: mysql-server
     state: started
     enabled: yes

  - name: to connect to db
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ password }}"
     login_host: "{{ host_name }}"
    ignore_errors: true
    register: my_sql_info

  - name: print mysql info
    ansible.builtin.debug:
     msg: "{{ my_sql_info }}"
    
  - name: to set root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ password }}"
    when: my_sql_info.failed is true
    




    
  