- name: To configure mysql
  hosts: mysql
  become: yes
  vars:
   host_address: mysql.app789.site
   password: ExpenseApp@1

  tasks:
  - name: To install Pymysql
    ansible.builtin.pip:
     name: 
     - PyMySQL
     executable: pip3.9