- name: To configure mysql
  hosts: mysql
  become: yes
  vars:
   host_address: mysql.app789.site
   password: ExpenseApp@1

  tasks:
  - name: To install Pymysql
    ansible.builtin.pip:
     name: 
     - PyMySQL
     executable: pip3.9

  - name: To install sql server
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: To start sql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  - name: To connect to sql server
    community.mysql.mysql_info:
     login_user: "root"
     login_passord: "{{ password }}"
     login_host: "{{ host_address }}"
     ignore_erroes: true
     register: mysql_info

  - name: To print the sql info
    ansible.builtin.package:
     msg: "{{ mysql_info }}"

  # - name: To change the default root password
  #   ansible.builtin.service:
  #    name: mysqld
  #    state: started
  #    enabled: yes
